up:
	docker compose -f docker-compose.yml --env-file .env.example up -d --build

down:
	docker compose -f docker-compose.yml --env-file .env.example down

logs:
	docker compose -f docker-compose.yml logs -f --tail=200
