name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: epiphany/services/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm@9
      - run: pnpm install
      - run: pnpm build

  web-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: epiphany/apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm@9
      - run: pnpm install
      - run: pnpm build

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (infer-image)
        working-directory: epiphany/services/infer-image
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q
      - name: Install deps (infer-video)
        working-directory: epiphany/services/infer-video
        run: |
          pip install -r requirements.txt
          pytest -q
      - name: Install deps (edit)
        working-directory: epiphany/services/edit
        run: |
          pip install -r requirements.txt
          pytest -q
      - name: Install deps (explain)
        working-directory: epiphany/services/explain
        run: |
          pip install -r requirements.txt
          pytest -q

  sdk-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: epiphany/packages/sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm@9
      - run: pnpm install
      - run: pnpm build

  docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -f epiphany/services/api/Dockerfile -t epiphany-api:ci epiphany
      - name: Build Web image
        run: docker build -f epiphany/apps/web/Dockerfile -t epiphany-web:ci epiphany
      - name: Build infer-image image
        run: docker build -f epiphany/services/infer-image/Dockerfile -t epiphany-infer-image:ci epiphany
      - name: Build infer-video image
        run: docker build -f epiphany/services/infer-video/Dockerfile -t epiphany-infer-video:ci epiphany
      - name: Build edit image
        run: docker build -f epiphany/services/edit/Dockerfile -t epiphany-edit:ci epiphany
      - name: Build explain image
        run: docker build -f epiphany/services/explain/Dockerfile -t epiphany-explain:ci epiphany
